[package]
name = "lut_extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
exr = "1.4.1"
clap = { version = "3.1.8", default-features = false, features=["std"] }
colorbox = { git = "https://github.com/cessen/colorbox", branch = "master" }
